/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CycleStatus {
  'lastFireFetchAt' : [] | [Timestamp],
  'lastRunAt' : [] | [Timestamp],
  'lastDeforestationFetchAt' : [] | [Timestamp],
  'nextRunAt' : [] | [Timestamp],
  'running' : boolean,
}
export interface DeforestationAlert {
  'id' : string,
  'lat' : Latitude,
  'lng' : Longitude,
  'alertDate' : Timestamp,
  'source' : string,
  'areaHectares' : number,
  'confidence' : bigint,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface FireDetection {
  'id' : string,
  'lat' : Latitude,
  'lng' : Longitude,
  'source' : string,
  'brightness' : number,
  'acqDate' : Timestamp,
  'confidence' : bigint,
}
export interface HttpHeader { 'value' : string, 'name' : string }
export interface HttpRequestResult {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type Latitude = number;
export type Longitude = number;
export type NoticeReason = { 'newEvent' : null } |
  { 'worsening' : null } |
  { 'escalating' : null } |
  { 'lingering' : null };
export interface NoticedEvent {
  'id' : string,
  'lat' : Latitude,
  'lng' : Longitude,
  'layer' : ThreatLayer,
  'summary' : string,
  'noticedAt' : Timestamp,
  'severity' : Severity,
  'payload' : string,
  'reason' : NoticeReason,
}
export type Result = { 'ok' : null } |
  { 'err' : Error };
export type Severity = { 'low' : null } |
  { 'high' : null } |
  { 'severe' : null } |
  { 'critical' : null } |
  { 'moderate' : null };
export type ThreatLayer = { 'fire' : null } |
  { 'deforestation' : null };
export interface ThreatSnapshot {
  'fires' : Array<FireDetection>,
  'fetchedAt' : Timestamp,
  'layer' : ThreatLayer,
  'deforestation' : Array<DeforestationAlert>,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : HttpRequestResult,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<HttpHeader>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '__CYCLE_INTERVAL_NS' : ActorMethod<[], bigint>,
  '__DEFAULT_AREA' : ActorMethod<[], string>,
  '__DEFAULT_FIRMS_KEY' : ActorMethod<[], string>,
  '__FIRMS_CSV_URL' : ActorMethod<[], string>,
  '__GFW_ALERTS_URL' : ActorMethod<[], string>,
  '__MAX_FEED' : ActorMethod<[], bigint>,
  '__accessControlState' : ActorMethod<[], any>,
  '__currentDeforestation' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<DeforestationAlert>
  >,
  '__currentFires' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<FireDetection>
  >,
  '__cycle' : ActorMethod<[], CycleStatus>,
  '__firmsApiKey' : ActorMethod<[], string>,
  '__lastDeforestationSnapshot' : ActorMethod<[], [] | [ThreatSnapshot]>,
  '__lastFireSnapshot' : ActorMethod<[], [] | [ThreatSnapshot]>,
  '__nextEventId' : ActorMethod<[], bigint>,
  '__noticedFeed' : ActorMethod<
    [[] | [bigint], [] | [bigint]],
    Array<NoticedEvent>
  >,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'fetchDeforestation' : ActorMethod<[], undefined>,
  'fetchFires' : ActorMethod<[], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCycleStatus' : ActorMethod<[], CycleStatus>,
  'getDeforestation' : ActorMethod<[], Array<DeforestationAlert>>,
  'getFires' : ActorMethod<[], Array<FireDetection>>,
  'getNoticedFeed' : ActorMethod<[[] | [bigint]], Array<NoticedEvent>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'runNoticingCycle' : ActorMethod<[], undefined>,
  'setFirmsApiKey' : ActorMethod<[string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];