/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Latitude = IDL.Float64;
export const Longitude = IDL.Float64;
export const Timestamp = IDL.Nat;
export const DeforestationAlert = IDL.Record({
  'id' : IDL.Text,
  'lat' : Latitude,
  'lng' : Longitude,
  'alertDate' : Timestamp,
  'source' : IDL.Text,
  'areaHectares' : IDL.Float64,
  'confidence' : IDL.Nat,
});
export const FireDetection = IDL.Record({
  'id' : IDL.Text,
  'lat' : Latitude,
  'lng' : Longitude,
  'source' : IDL.Text,
  'brightness' : IDL.Float64,
  'acqDate' : Timestamp,
  'confidence' : IDL.Nat,
});
export const CycleStatus = IDL.Record({
  'lastFireFetchAt' : IDL.Opt(Timestamp),
  'lastRunAt' : IDL.Opt(Timestamp),
  'lastDeforestationFetchAt' : IDL.Opt(Timestamp),
  'nextRunAt' : IDL.Opt(Timestamp),
  'running' : IDL.Bool,
});
export const ThreatLayer = IDL.Variant({
  'fire' : IDL.Null,
  'deforestation' : IDL.Null,
});
export const ThreatSnapshot = IDL.Record({
  'fires' : IDL.Vec(FireDetection),
  'fetchedAt' : Timestamp,
  'layer' : ThreatLayer,
  'deforestation' : IDL.Vec(DeforestationAlert),
});
export const Severity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'severe' : IDL.Null,
  'critical' : IDL.Null,
  'moderate' : IDL.Null,
});
export const NoticeReason = IDL.Variant({
  'newEvent' : IDL.Null,
  'worsening' : IDL.Null,
  'escalating' : IDL.Null,
  'lingering' : IDL.Null,
});
export const NoticedEvent = IDL.Record({
  'id' : IDL.Text,
  'lat' : Latitude,
  'lng' : Longitude,
  'layer' : ThreatLayer,
  'summary' : IDL.Text,
  'noticedAt' : Timestamp,
  'severity' : Severity,
  'payload' : IDL.Text,
  'reason' : NoticeReason,
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
export const HttpRequestResult = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : HttpRequestResult,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(HttpHeader),
});

export const idlService = IDL.Service({
  '__CYCLE_INTERVAL_NS' : IDL.Func([], [IDL.Int], ['query']),
  '__DEFAULT_AREA' : IDL.Func([], [IDL.Text], ['query']),
  '__DEFAULT_FIRMS_KEY' : IDL.Func([], [IDL.Text], ['query']),
  '__FIRMS_CSV_URL' : IDL.Func([], [IDL.Text], ['query']),
  '__GFW_ALERTS_URL' : IDL.Func([], [IDL.Text], ['query']),
  '__MAX_FEED' : IDL.Func([], [IDL.Nat], ['query']),
  '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
  '__currentDeforestation' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(DeforestationAlert)],
      ['query'],
    ),
  '__currentFires' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(FireDetection)],
      ['query'],
    ),
  '__cycle' : IDL.Func([], [CycleStatus], ['query']),
  '__firmsApiKey' : IDL.Func([], [IDL.Text], ['query']),
  '__lastDeforestationSnapshot' : IDL.Func(
      [],
      [IDL.Opt(ThreatSnapshot)],
      ['query'],
    ),
  '__lastFireSnapshot' : IDL.Func([], [IDL.Opt(ThreatSnapshot)], ['query']),
  '__nextEventId' : IDL.Func([], [IDL.Nat], ['query']),
  '__noticedFeed' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(NoticedEvent)],
      ['query'],
    ),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'fetchDeforestation' : IDL.Func([], [], []),
  'fetchFires' : IDL.Func([], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCycleStatus' : IDL.Func([], [CycleStatus], ['query']),
  'getDeforestation' : IDL.Func([], [IDL.Vec(DeforestationAlert)], ['query']),
  'getFires' : IDL.Func([], [IDL.Vec(FireDetection)], ['query']),
  'getNoticedFeed' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(NoticedEvent)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'runNoticingCycle' : IDL.Func([], [], []),
  'setFirmsApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Latitude = IDL.Float64;
  const Longitude = IDL.Float64;
  const Timestamp = IDL.Nat;
  const DeforestationAlert = IDL.Record({
    'id' : IDL.Text,
    'lat' : Latitude,
    'lng' : Longitude,
    'alertDate' : Timestamp,
    'source' : IDL.Text,
    'areaHectares' : IDL.Float64,
    'confidence' : IDL.Nat,
  });
  const FireDetection = IDL.Record({
    'id' : IDL.Text,
    'lat' : Latitude,
    'lng' : Longitude,
    'source' : IDL.Text,
    'brightness' : IDL.Float64,
    'acqDate' : Timestamp,
    'confidence' : IDL.Nat,
  });
  const CycleStatus = IDL.Record({
    'lastFireFetchAt' : IDL.Opt(Timestamp),
    'lastRunAt' : IDL.Opt(Timestamp),
    'lastDeforestationFetchAt' : IDL.Opt(Timestamp),
    'nextRunAt' : IDL.Opt(Timestamp),
    'running' : IDL.Bool,
  });
  const ThreatLayer = IDL.Variant({
    'fire' : IDL.Null,
    'deforestation' : IDL.Null,
  });
  const ThreatSnapshot = IDL.Record({
    'fires' : IDL.Vec(FireDetection),
    'fetchedAt' : Timestamp,
    'layer' : ThreatLayer,
    'deforestation' : IDL.Vec(DeforestationAlert),
  });
  const Severity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'severe' : IDL.Null,
    'critical' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const NoticeReason = IDL.Variant({
    'newEvent' : IDL.Null,
    'worsening' : IDL.Null,
    'escalating' : IDL.Null,
    'lingering' : IDL.Null,
  });
  const NoticedEvent = IDL.Record({
    'id' : IDL.Text,
    'lat' : Latitude,
    'lng' : Longitude,
    'layer' : ThreatLayer,
    'summary' : IDL.Text,
    'noticedAt' : Timestamp,
    'severity' : Severity,
    'payload' : IDL.Text,
    'reason' : NoticeReason,
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const HttpHeader = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const HttpRequestResult = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : HttpRequestResult,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(HttpHeader),
  });
  
  return IDL.Service({
    '__CYCLE_INTERVAL_NS' : IDL.Func([], [IDL.Int], ['query']),
    '__DEFAULT_AREA' : IDL.Func([], [IDL.Text], ['query']),
    '__DEFAULT_FIRMS_KEY' : IDL.Func([], [IDL.Text], ['query']),
    '__FIRMS_CSV_URL' : IDL.Func([], [IDL.Text], ['query']),
    '__GFW_ALERTS_URL' : IDL.Func([], [IDL.Text], ['query']),
    '__MAX_FEED' : IDL.Func([], [IDL.Nat], ['query']),
    '__accessControlState' : IDL.Func([], [IDL.Reserved], ['query']),
    '__currentDeforestation' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(DeforestationAlert)],
        ['query'],
      ),
    '__currentFires' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(FireDetection)],
        ['query'],
      ),
    '__cycle' : IDL.Func([], [CycleStatus], ['query']),
    '__firmsApiKey' : IDL.Func([], [IDL.Text], ['query']),
    '__lastDeforestationSnapshot' : IDL.Func(
        [],
        [IDL.Opt(ThreatSnapshot)],
        ['query'],
      ),
    '__lastFireSnapshot' : IDL.Func([], [IDL.Opt(ThreatSnapshot)], ['query']),
    '__nextEventId' : IDL.Func([], [IDL.Nat], ['query']),
    '__noticedFeed' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(NoticedEvent)],
        ['query'],
      ),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'fetchDeforestation' : IDL.Func([], [], []),
    'fetchFires' : IDL.Func([], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCycleStatus' : IDL.Func([], [CycleStatus], ['query']),
    'getDeforestation' : IDL.Func([], [IDL.Vec(DeforestationAlert)], ['query']),
    'getFires' : IDL.Func([], [IDL.Vec(FireDetection)], ['query']),
    'getNoticedFeed' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(NoticedEvent)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'runNoticingCycle' : IDL.Func([], [], []),
    'setFirmsApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };