/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import type { ExternalBlob } from "@caffeineai/object-storage";
export type { ExternalBlob } from "@caffeineai/object-storage";
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface HttpRequestResult {
    status: bigint;
    body: Uint8Array;
    headers: Array<HttpHeader>;
}
export interface FireDetection {
    id: string;
    lat: Latitude;
    lng: Longitude;
    source: string;
    brightness: number;
    acqDate: Timestamp;
    confidence: bigint;
}
export interface NoticedEvent {
    id: string;
    lat: Latitude;
    lng: Longitude;
    layer: ThreatLayer;
    summary: string;
    noticedAt: Timestamp;
    severity: Severity;
    payload: string;
    reason: NoticeReason;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface CycleStatus {
    lastFireFetchAt?: Timestamp;
    lastRunAt?: Timestamp;
    lastDeforestationFetchAt?: Timestamp;
    nextRunAt?: Timestamp;
    running: boolean;
}
export type Latitude = number;
export interface HttpHeader {
    value: string;
    name: string;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface ThreatSnapshot {
    fires: Array<FireDetection>;
    fetchedAt: Timestamp;
    layer: ThreatLayer;
    deforestation: Array<DeforestationAlert>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: HttpRequestResult;
}
export interface DeforestationAlert {
    id: string;
    lat: Latitude;
    lng: Longitude;
    alertDate: Timestamp;
    source: string;
    areaHectares: number;
    confidence: bigint;
}
export type Longitude = number;
export enum NoticeReason {
    newEvent = "newEvent",
    worsening = "worsening",
    escalating = "escalating",
    lingering = "lingering"
}
export enum Severity {
    low = "low",
    high = "high",
    severe = "severe",
    critical = "critical",
    moderate = "moderate"
}
export enum ThreatLayer {
    fire = "fire",
    deforestation = "deforestation"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    __CYCLE_INTERVAL_NS(): Promise<bigint>;
    __DEFAULT_AREA(): Promise<string>;
    __DEFAULT_FIRMS_KEY(): Promise<string>;
    __FIRMS_CSV_URL(): Promise<string>;
    __GFW_ALERTS_URL(): Promise<string>;
    __MAX_FEED(): Promise<bigint>;
    __accessControlState(): Promise<any>;
    __currentDeforestation(io: bigint | null, count: bigint | null): Promise<Array<DeforestationAlert>>;
    __currentFires(io: bigint | null, count: bigint | null): Promise<Array<FireDetection>>;
    __cycle(): Promise<CycleStatus>;
    __firmsApiKey(): Promise<string>;
    __lastDeforestationSnapshot(): Promise<ThreatSnapshot | null>;
    __lastFireSnapshot(): Promise<ThreatSnapshot | null>;
    __nextEventId(): Promise<bigint>;
    __noticedFeed(io: bigint | null, count: bigint | null): Promise<Array<NoticedEvent>>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    fetchDeforestation(): Promise<void>;
    fetchFires(): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getCycleStatus(): Promise<CycleStatus>;
    getDeforestation(): Promise<Array<DeforestationAlert>>;
    getFires(): Promise<Array<FireDetection>>;
    getNoticedFeed(limit: bigint | null): Promise<Array<NoticedEvent>>;
    isCallerAdmin(): Promise<boolean>;
    runNoticingCycle(): Promise<void>;
    setFirmsApiKey(key: string): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { CycleStatus as _CycleStatus, DeforestationAlert as _DeforestationAlert, Error as _Error, FireDetection as _FireDetection, Latitude as _Latitude, Longitude as _Longitude, NoticeReason as _NoticeReason, NoticedEvent as _NoticedEvent, Result as _Result, Severity as _Severity, ThreatLayer as _ThreatLayer, ThreatSnapshot as _ThreatSnapshot, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async __CYCLE_INTERVAL_NS(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__CYCLE_INTERVAL_NS();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__CYCLE_INTERVAL_NS();
            return result;
        }
    }
    async __DEFAULT_AREA(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__DEFAULT_AREA();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__DEFAULT_AREA();
            return result;
        }
    }
    async __DEFAULT_FIRMS_KEY(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__DEFAULT_FIRMS_KEY();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__DEFAULT_FIRMS_KEY();
            return result;
        }
    }
    async __FIRMS_CSV_URL(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__FIRMS_CSV_URL();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__FIRMS_CSV_URL();
            return result;
        }
    }
    async __GFW_ALERTS_URL(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__GFW_ALERTS_URL();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__GFW_ALERTS_URL();
            return result;
        }
    }
    async __MAX_FEED(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__MAX_FEED();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__MAX_FEED();
            return result;
        }
    }
    async __accessControlState(): Promise<any> {
        if (this.processError) {
            try {
                const result = await this.actor.__accessControlState();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__accessControlState();
            return result;
        }
    }
    async __currentDeforestation(arg0: bigint | null, arg1: bigint | null): Promise<Array<DeforestationAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.__currentDeforestation(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__currentDeforestation(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __currentFires(arg0: bigint | null, arg1: bigint | null): Promise<Array<FireDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.__currentFires(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__currentFires(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async __cycle(): Promise<CycleStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.__cycle();
                return from_candid_CycleStatus_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__cycle();
            return from_candid_CycleStatus_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async __firmsApiKey(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.__firmsApiKey();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__firmsApiKey();
            return result;
        }
    }
    async __lastDeforestationSnapshot(): Promise<ThreatSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.__lastDeforestationSnapshot();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__lastDeforestationSnapshot();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async __lastFireSnapshot(): Promise<ThreatSnapshot | null> {
        if (this.processError) {
            try {
                const result = await this.actor.__lastFireSnapshot();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__lastFireSnapshot();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async __nextEventId(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.__nextEventId();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__nextEventId();
            return result;
        }
    }
    async __noticedFeed(arg0: bigint | null, arg1: bigint | null): Promise<Array<NoticedEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.__noticedFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.__noticedFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n21(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async fetchDeforestation(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchDeforestation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchDeforestation();
            return result;
        }
    }
    async fetchFires(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchFires();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchFires();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCycleStatus(): Promise<CycleStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCycleStatus();
                return from_candid_CycleStatus_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCycleStatus();
            return from_candid_CycleStatus_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeforestation(): Promise<Array<DeforestationAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeforestation();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeforestation();
            return result;
        }
    }
    async getFires(): Promise<Array<FireDetection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFires();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFires();
            return result;
        }
    }
    async getNoticedFeed(arg0: bigint | null): Promise<Array<NoticedEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNoticedFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNoticedFeed(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async runNoticingCycle(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runNoticingCycle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runNoticingCycle();
            return result;
        }
    }
    async setFirmsApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFirmsApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFirmsApiKey(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_CycleStatus_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CycleStatus): CycleStatus {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_NoticeReason_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticeReason): NoticeReason {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_NoticedEvent_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NoticedEvent): NoticedEvent {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Severity_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Severity): Severity {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatLayer_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatLayer): ThreatLayer {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ThreatSnapshot_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ThreatSnapshot): ThreatSnapshot {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ThreatSnapshot]): ThreatSnapshot | null {
    return value.length === 0 ? null : from_candid_ThreatSnapshot_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    lat: _Latitude;
    lng: _Longitude;
    layer: _ThreatLayer;
    summary: string;
    noticedAt: _Timestamp;
    severity: _Severity;
    payload: string;
    reason: _NoticeReason;
}): {
    id: string;
    lat: Latitude;
    lng: Longitude;
    layer: ThreatLayer;
    summary: string;
    noticedAt: Timestamp;
    severity: Severity;
    payload: string;
    reason: NoticeReason;
} {
    return {
        id: value.id,
        lat: value.lat,
        lng: value.lng,
        layer: from_candid_ThreatLayer_n8(_uploadFile, _downloadFile, value.layer),
        summary: value.summary,
        noticedAt: value.noticedAt,
        severity: from_candid_Severity_n13(_uploadFile, _downloadFile, value.severity),
        payload: value.payload,
        reason: from_candid_NoticeReason_n15(_uploadFile, _downloadFile, value.reason)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastFireFetchAt: [] | [_Timestamp];
    lastRunAt: [] | [_Timestamp];
    lastDeforestationFetchAt: [] | [_Timestamp];
    nextRunAt: [] | [_Timestamp];
    running: boolean;
}): {
    lastFireFetchAt?: Timestamp;
    lastRunAt?: Timestamp;
    lastDeforestationFetchAt?: Timestamp;
    nextRunAt?: Timestamp;
    running: boolean;
} {
    return {
        lastFireFetchAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastFireFetchAt)),
        lastRunAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastRunAt)),
        lastDeforestationFetchAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.lastDeforestationFetchAt)),
        nextRunAt: record_opt_to_undefined(from_candid_opt_n4(_uploadFile, _downloadFile, value.nextRunAt)),
        running: value.running
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fires: Array<_FireDetection>;
    fetchedAt: _Timestamp;
    layer: _ThreatLayer;
    deforestation: Array<_DeforestationAlert>;
}): {
    fires: Array<FireDetection>;
    fetchedAt: Timestamp;
    layer: ThreatLayer;
    deforestation: Array<DeforestationAlert>;
} {
    return {
        fires: value.fires,
        fetchedAt: value.fetchedAt,
        layer: from_candid_ThreatLayer_n8(_uploadFile, _downloadFile, value.layer),
        deforestation: value.deforestation
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    severe: null;
} | {
    critical: null;
} | {
    moderate: null;
}): Severity {
    return "low" in value ? Severity.low : "high" in value ? Severity.high : "severe" in value ? Severity.severe : "critical" in value ? Severity.critical : "moderate" in value ? Severity.moderate : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newEvent: null;
} | {
    worsening: null;
} | {
    escalating: null;
} | {
    lingering: null;
}): NoticeReason {
    return "newEvent" in value ? NoticeReason.newEvent : "worsening" in value ? NoticeReason.worsening : "escalating" in value ? NoticeReason.escalating : "lingering" in value ? NoticeReason.lingering : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n19(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fire: null;
} | {
    deforestation: null;
}): ThreatLayer {
    return "fire" in value ? ThreatLayer.fire : "deforestation" in value ? ThreatLayer.deforestation : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NoticedEvent>): Array<NoticedEvent> {
    return value.map((x)=>from_candid_NoticedEvent_n11(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
